name: attendify
description: "Ultimate attendance checker for any usage"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.1
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  assets:
    - assets/icons/
  generate: true
  uses-material-design: true

flutter_gen:
  output: lib/gen/

  integrations:
    image: true
    flutter_svg: true

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/icon.png"
  android: true
  ios: true
  android_gravity: center
  fullscreen: true
