name: Build release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get
        working-directory: flutter_app

      - name: Build release APK
        run: flutter build apk --release
        working-directory: flutter_app

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ github.sha }}
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
